/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SimpleVectorGraphicsTest {
    @Test public void testSomeLibraryMethod() {
        SimpleVectorGraphics classUnderTest = new SimpleVectorGraphics();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
